plugins {
    alias(libs.plugins.android.library)
    id 'maven-publish'
}

group = 'com.github.girish3'

android {
    compileSdk 37
    namespace "com.android.girish.vlog"

    defaultConfig {
        minSdk 26
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    publishing {
        singleVariant('release') {
            withSourcesJar()
        }
    }
}

dependencies {
    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.androidx.test.espresso.core
}

afterEvaluate {
    publishing {
        repositories {
            maven {
                name = "GitHubPackages"
                url = uri("https://maven.pkg.github.com/soramitsukhmer-lab/vlog")
                credentials {
                    username = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
                    password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
                }
            }
        }
        publications {
            release(MavenPublication) {
                from components.release
                groupId = 'com.github.girish3'
                artifactId = 'library-no-op'
                version = android.defaultConfig.versionName
            }
        }
    }
}
