plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace "com.girish.vlogsample"
    compileSdk 37
    defaultConfig {
        applicationId "com.girish.vlogsample"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation libs.androidx.appcompat
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.core.ktx
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.runner
    androidTestImplementation libs.androidx.test.espresso.core

    // Vlog library
    //debugImplementation 'com.github.girish3.Vlog:library:v0.3'
    //releaseImplementation 'com.github.girish3.Vlog:library-no-op:v0.3'
    // implementation project(path: ':library-no-op')
    implementation project(path: ':library')
}
